# Basic Config
esphome:
  name: tvoutlet
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: seekingConnections
  password: ""
  ap:
    ssid: "tv outlet"
    password: ""

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
api:
ota:

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "tv outlet Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "tv outlet Status"

sensor:
  - platform: wifi_signal
    name: "tv outlet WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "tv outlet Current"
      accuracy_decimals: 1
    voltage:
      name: "tv outlet Voltage"
      accuracy_decimals: 1
    power:
      name: "tv outlet Power"
      accuracy_decimals: 1
      id: outlet01Power
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: outlet01Power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
time:
- platform: sntp
  id: my_time

switch:
  - platform: gpio
    name: "tv outlet Relay"
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13