# Basic Config
esphome:
  name: outlet01
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ssid
  password: "pw"
  ap:
    ssid: "outlet 01"
    password: "pw"

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
api:
ota:

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "outlet 01 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "outlet 01 Status"

sensor:
  - platform: wifi_signal
    name: "outlet 01 WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "outlet 01 Current"
      accuracy_decimals: 1
    voltage:
      name: "outlet 01 Voltage"
      accuracy_decimals: 1# Basic Config
esphome:
  name: outlet01
  platform: ESP8266
  board: esp01_1m